version: '3.9'

services:
  dash:
    command: python3 main.py
    image: tuktik6326/dash-demo-2:a2.0
    build: 
      context: .
      dockerfile: Car.Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 4000:80