version: '3.9'

services:
  dash:
    command: python3 main.py
    image: tuktik6326/dash-demo-2:a2.0 
    environment:
      - HOST=0.0.0.0
      - PORT=80
  labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.dash-st124383.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is dash-st124383
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.dash-st124383.rule=Host(`st124383.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.dash-st124383.tls=true
      - traefik.http.routers.dash-st124383.tls.certresolver=production
      - traefik.http.routers.dash-st124383.entrypoints=websecure
      # This define network. You would need to keep it like this.
  networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true